# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInvoiceJson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.IntegerField()),
                ('invoice_number', models.CharField(max_length=500)),
                ('date_due', models.DateField()),
                ('invoice_date', models.DateField()),
                ('amount', models.FloatField()),
                ('fine', models.FloatField()),
                ('discount', models.FloatField()),
                ('invoice_amount', models.FloatField()),
            ],
        ),
    ]
